name: Test Build on Multiple OS

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers and dependencies
      uses: microsoft/playwright-github-action@v1
      with:
        install-deps: true # This installs the required dependencies for Playwright

    - name: Start local frontend server (Windows)
      if: runner.os == 'Windows'
      run: Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run", "dev"
      shell: pwsh  # Using PowerShell on Windows

    - name: Start local frontend server (Linux/Mac)
      if: runner.os != 'Windows'
      run: npm run dev &
      shell: bash

    - name: Wait for server to be ready
      run: sleep 15

    - name: Run build
      run: npm run build
    
    - name: Execute dist/cli.js
      run: npm run start

    - name: Verify build
      run: ls -la ./.viewsnap/snapshots.html  # or the directory where the build artifacts are generated